# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: Deploying flask app
  displayName: 'Deploy flask app in k8s cluster'
  
- task: CopyFiles@2
  displayName: 'Copy deployment file to bastion server'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: 'flask-app-deployment.yaml'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/deployment'

- task: SSH@0
  displayName: 'Copy deployment file to bastion server'
  inputs:
    sshEndpoint: 'bastion-server'
    runOptions: 'commands'
    commands: |
      scp $(Build.ArtifactStagingDirectory)/deployment/flask-app-deployment.yaml azureuser@ccp-pulse-dev-bastion.canadacentral.cloudapp.azure.com:/home/azureuser/flask-demo-app/flask-app-deployment.yaml

- task: KubernetesManifest@0
  displayName: 'Apply K8s deployment'
  inputs:
    connectionType: 'None'
    command: 'apply'
    arguments: '-f /home/azureuser/flask-demo-app/flask-app-deployment.yaml'
    secrets: 'isuru-rathnayake'
